<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\PersonalLibrary.Domain\PersonalLibrary.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Books\Commands\" />
		<Folder Include="Books\Queries\" />
		<Folder Include="Books\Repositories\" />
		<Folder Include="Books\Services\" />
		<Folder Include="Common\Services\" />
		<Folder Include="Identity\Queries\" />
		<Folder Include="Identity\Repositories\" />
		<Folder Include="Imports\Commands\" />
		<Folder Include="Imports\Queries\" />
		<Folder Include="Imports\Repositories\" />
		<Folder Include="Imports\Services\" />
		<Folder Include="Libraries\Commands\" />
		<Folder Include="Libraries\Queries\" />
		<Folder Include="Libraries\Repositories\" />
		<Folder Include="Libraries\Services\" />
		<Folder Include="Loans\Commands\" />
		<Folder Include="Loans\Queries\" />
		<Folder Include="Loans\Repositories\" />
		<Folder Include="Loans\Services\" />
	</ItemGroup>

</Project>
